language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: V8cnpPrOsVd97gG6KhgE1J3VmEWlDm6Sb9FnPk7NTeXaAMql+htl1Xe+aFsoCXuVr8QpzJ1i5O8JjoLDniVHoTJTBDX0ITv7MT+y+hXC8UJFqSXrtJVOpV1WyCnPf18/PqsUClI9lslKa/rs4eTJhgwZJdkw9Yot2PVTCkHoDhHKzU3uAjpKMeH5xIcpaMXA1DU2FiNQfRdVj2qgLAgFzZNX85z/eb62ZnsXKZbkuN6KGTGOX/2uGYMXDUrtFYJ7ZWpfgDCxy7pibLw99ddSfBgxhkjqZ1Pknrzl6egPx9NGaKwq4torw6sdgUPltrmxTl2BP9ag9NNFwyYg6AfAIYe33C2Zwx4cLNxDc2Jo5QxXsfNkMxUZtL8Ivp27NdT3vhjRr1V0jFTxl8Oj6z3b7z+zV8lKcjlStXVHjj1QSJyfelmmA1aLyIPr+aztP5O06ykheGHyvB60pPTch6wTp4ILaWoFD6f0DeUAmVWoEgpf0G5sGQvCDdWdfwf9lS5Q3E3Y41v4m68x72C6+qF/w7EYlPK2dSIiyNwuBGhDQbO8r107VcisHVW45TsZUB24/ItAIgPlytW/lqHI9lMyFWBMI2euDSj2Z3uY5MqeU4/RLS5rpag4bXpjQMgW7nDmdb3Tx5rldmFVEefckqFpE2hOpwzNpftRzg5VxYPCQqI=
  app: node-demo-promact
  on:
    repo: rushi216/node-demo
