language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: "AKuIqGOBnlsmFz7wMiiUIvGMJOfEcJ85u4A0H0aFwjNEQWnbdV5jqzXCrJFNNDlef84w55QQ8ni6aWq8IxSLMAJqoudmU7sJ/mfgpXElGF+j6J79HxqANudU5ZQT5/FbtJN3J1gMQvN+jS4/93l0HiqO2s+8ofiDl/5HPO7bnaacx0EK6uAJKPeVDFKH6gbQY/uC+evlBc7cSbTpzhvSHBkQTu5bYQH2Yeg+XZ3rPY/DqeVJz4cpIOUmWciRIfHldIqpw8ONELyTDdcBGulXfmz9dugRNjfB8hN4uCfcQahg4547sztsK/maPcc9vEhDPVMS6ize3dZe6fBcGxl106/hsrN0VQaCu1ZRJu/4C7UFj+cIOo78VwIAElnahS1kEXH58mONQUJDenmBzb9oQgL6PPUsFOwJKHStHYQcUZJ+l9oPkAp5bEry2g4h5XyiMW26UV7tjZOPgbVclT2t7f23KkOFi4BEXl/wIVYn7vIQbCxVeVIYAc67NCUJOxLhEST4FFY2Sz6ibqpcC9cC3TntsdS9jeWAl/VKFSxel/DbF5sGSRN75yU2zSYU6ehYBGAlQ/t/jeatyMnxOM4B8uC77m9g4kyday6ZzIcJ9vBCFo/X1U8VTLYM+mxeGEEBTClDbpxmhgN2R/db1kFhOS3TKj1pM6T1IJktE54wKLo="
  app: node-demo-promact
  on:
    repo: rushi216/node-demo
