language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: Xa0c5x8nT224LhtImn2irR8QBNI0LyvfbImg8ftkES6KlOsxgOJzk3wntjyycRRMk8h1tjMd323Q66xo9GFVy7R/SZRZRrZo/jloTLnxuz/rGJsypTSaQjKNLVZmYAlpeYLdLuOX6Cbh1oZyVDryvg4HRC09PzoqiVt0EWMpj0LQTOhBJQiTbXII/MswMTu/5B3lvSdqYiAOutyZFhIKzdRvA4WRC+Axx9VE/s/DwKlH5EU6dIGrMiPSTCov+lqklLPi/JygSf1mw3NVcwLClJAExz/dQaEk+NAjm+byOIqH4xN8ZN1Zd8oJdmW9KujUDbbmVus2s8qo2z6ey3rkJ82hSd60JPNOaY9bBjlM47y16ed1DSQM/jmyYhDXwA6hmbfZYESFqd4002T8z++PdVzARzKxNEoV/pLgFWe1RhPQxC4X1tsR70vMe+YGZlVdaRHiiIw6EfeYJPeFc1HW9pd1FNzjRYRwKHKsJWMdIaquXRO4YCe2QwHIwwDcoZdZfeeZPDH+HC6mCx3coO6arWmRLnDS6McCp5cm8gagro3giFNVftCaHrF8z+Gv2mnTuXmQK86+l9qp7rCiWWkigrYpZqEnRvdH2A27TKNPxIFiWR83HE2T4IsNEbeNkB0kmE/WuEtoZGpvYc4Ypx+Hj5lRDR2m8CM45iXLsoX1SfU=
  app: node-demo-promact
  on:
    repo: rushi216/node-demo
