language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: node-demo-promact
  api_key:
    secure: ab6s57MIXpHkkSU4r1b7dvshYPSw2oY53ml7HtJt4CMjPiXaj7IrgomZRt7HC4cnL2SKd4sNsLJao9ZuEZ8/KovYX03ezGkhZRFj+NsVjLp0QOYx6FlxwMOTHCF2kxZMGZ+EyqhgsdXq8JVGCjL8+Psl9bzSvm2Pyvusz1+6cTT8muhBDeYdUuUyIC4IYzplrZ6MXieSAjtoBUJHgxWwSuUgo3CWbC2U9ig8d5Cbi55X7OXlRHCnozx5yH3FBUkT1+6KiZ3Wn2CzeQicMzbF3mrNTuel9YVQQ+Pr/beGOmACaoX9yRN8BGy/YGjDuQiW2UrCd08BGZHD3KYrcBHG0S8XqIBwZ9Ktv5tYwBplXf4GSIg6TKJxxMwHBG1XSl2vTQTUvYilfXFBrA4s5kwK16n0lq/spFFhBKgXAb7AnTa0FOLbOzu37bI4AUuFx6+k4hD80Uyk+HRz9i898W+p1RIjUmheIgTELwrVwa7LsSyIBLkBgMrUy29hx3sZWAv5kqDXyDQ7PZTglXyp0ygSjQtJXvsWpU81t1oW1gB8e6+4XMdqj6McMim4U8Pmf8/6gh6m6FPHZJD23W1fWuSMkXYX4AjyAKUDfP4+me+KXOaQruKXBxdZ3rPXo89p4RQWuzqRQZ6Pri7QaY17AmgEq5MfooAD8vkGeD2y98nU2WQ=
