language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: aaf9tOCR5a8SX5IJHASukD5ze45MtWM4taa3uCWfIH4IRw+gcBBDIVL3BPVZ18gegYxCVRkRDLB61BlY3CMGiLWCbHjeJRX/G/EEx9LH4Ue3Oxyy0LolwI5NX1+53gAAGWwRhhtSB/vS7tM1yE/72BH8D3Ouub7rehBLUbkdLdnAvp6mpYA9X27t0CajdYv+Qz+h24JsReizUFV9kPDe2oaD0GtnbXy33QAHLpmcmJYgom03JwZWXug+iEXIrV8af1g+fyPR0TMcFhwK1cYwq8brmRvcjE27LQuSF+ew7bg9mfbq5201BeJf/IWxz8GJTv12Q8EbRbRcT3w94ocRfZqeVMKAeG/XmXxfFVzFEGy+nEF4Y3pRk+vUUIoBeObTh+lYKDTxmm08t21VTBNugI2uWtxH8vVLeC/lcQ4znh5681QgxsW+au6RE0d1Ftfl09PPKATI8qHTg+FKwLAfhTTnlwG3i4petCd/GxeRLbQ1jWR5/mCmwbQpQSm86ldNXTPOioNBNu62sacaCcLtsuys3dzLk0sUkSJvzrvCY/LPCW2k/e3yiknaglrZj6UabtRh4Nvg39sJL7mQGossglgJrB6GLnj4WReIyLk6dlXbP0+zPCK0YqxdEkArmg/poepry4RSASKi7ZjzxFXPe8+emwSQ2LG+TctVK8MmEeA=
  app: node-demo-promact
  on:
    repo: rushi216/node-demo
